### ISSUE TITLE
[Question] Getting raw and masked input values

### ISSUE THREAD

**Issue by tolu360** [benhurott/react-native-masked-text#10]
Hello, from the README, it is not particularly clear to me, the proper way to get values from the inputs e.g.

```javascript
import React, {Component} from 'react';

// import the component
import {TextInputMask} from 'react-native-masked-text';

export default class MyComponent extends Component {
    constructor(props) {
        super(props);
    }

    isValid() {
        // isValid method returns if the inputed value is valid.
        // Ex: if you input 40/02/1990 30:20:20, it will return false
        //     because in this case, the day and the hour is invalid.
        let valid = this.refs['myDateText'].isValid();

        // get converted value. Using type=datetime, it returns the moment object.
        // If it's using type=money, it returns a Number object.
        let rawValue = this.refs['myDateText'].getRawValue();
    }

    render() {
        // the type is required but options is required only for some specific types.
        return (
            <TextInputMask 
                ref={'myDateText'}
                type={'datetime'}
                options={{
                    format: 'DD-MM-YYYY HH:mm:ss'
                }} />
        );
    }
}
```

From the above usage example, how and when is the method `isValid()` called? And how should `onChangeText` be used? Thanks

**Comment by benhurott** [comment]
Hi,

You will use `onChange` if you want to get the value with mask.
If you want the raw value (ex: the Number value of Money Mask), you must use `getRawValue`.

The `isValid` method is a helper to validate the input for business logic (ex: your form must not be sent if a invalid date is inputed for datetime mask) so you check `isValid` method to validate the value. The method returns a boolean value.

**Comment by benhurott** [comment]
Hi, if you want more explanations, contact me =).

**Comment by wesleyguirra** [comment]
How to use this? example, please.

**Comment by renancompuece** [comment]
Conseguiu , cara ?

**Comment by jaburcodes** [comment]
plz help

**Comment by wesleyguirra** [comment]
It's been a while since I used the library, but I did it without the examples, I'll find where I used it then I'll put it here, maybe it could be used as an example.
