### ISSUE TITLE
Is possible use TextInputMask only as text?

### ISSUE THREAD

**Issue by ncampuzano** [benhurott/react-native-masked-text#100]
Hello,

In my react native app I have inputs and texts that needs currency format. This component works fantastic with Inputs, but there is a way to use formatter function on Text tag, or use TextInputMask only as Text tag (I mean disable editing, remove underscore line and so on)?

**Comment by benhurott** [comment]
Hi, yes.

Look at this [DOCUMENTATION](https://github.com/benhurott/react-native-masked-text#usage-textmask)

(I need to improve this doc =P)
