### ISSUE TITLE
credit-card type

### ISSUE THREAD

**Issue by StanislavVoronov** [benhurott/react-native-masked-text#103]
when I removing the number in the middle of the string and add again, it doesn't add it to next block of numbers and adds number in current block, replacing. 

Example of what i say
	const v = value.replace(/\s+/g, '').replace(/[^0-9]/gi, '');
	const matches = v.match(/\d{4,16}/g);
	const match = (matches && matches[0]) || '';
	const parts = [];
	for (let i = 0, len = match.length; i < len; i += 4) {
		parts.push(match.substring(i, i + 4));
	}
	if (parts.length) {
		return parts.join(' ');
	} else {
		return value;
	}
it adds number in next four number block if current block is full

**Comment by benhurott** [comment]
Hi!

This a duplicated issue of #35 , I'll work on this asap.
