### ISSUE TITLE
MaskService.toMask with type 'datetime'

### ISSUE THREAD

**Issue by StanislavVoronov** [benhurott/react-native-masked-text#104]
I try to get datetime formatted string
I use MaskService.toMask('datetime', '10-10-2018', { format: 'YYYY-MM-DD' }));
and get 101-0-20. 
What do I make wrong?

**Comment by benhurott** [comment]
Hi, this function does not understand and convert dates, just mask the value you passed.
The format is for validation methods.

To work with dates and format a value, use a third part lib like momentjs.
