### ISSUE TITLE
getRawValue is not a function

### ISSUE THREAD

**Issue by BradSelfridge** [benhurott/react-native-masked-text#105]
I copied and pasted your npm datetime example and the code errors out with the following message: "this.myDateText.getRawValue is not a function". 

I logged out the contents of "this.myDateText" and I get this: 

{measure: ƒ, measureInWindow: ƒ, measureLayout: ƒ, setNativeProps: ƒ, focus: ƒ, …}
TimerMixin_immediates: null
TimerMixin_intervals: null
TimerMixin_rafs: null
TimerMixin_timeouts: null
blur: ƒ ()
cancelAnimationFrame: ƒ ()
clear: ƒ ()
clearImmediate: ƒ ()
clearInterval: ƒ ()
clearTimeout: ƒ ()
context: {isInAParentText: false, onFocusRequested: undefined, focusEmitter: undefined}
focus: ƒ ()
isFocused: ƒ ()
measure: ƒ ()
measureInWindow: ƒ ()
measureLayout: ƒ ()
props: {keyboardType: "numeric", refInput: ƒ, type: "datetime", options: {…}, onChangeText: ƒ, …}
refs: {}
requestAnimationFrame: ƒ ()
setImmediate: ƒ ()
setInterval: ƒ ()
setNativeProps: ƒ ()
setTimeout: ƒ ()
state: null
updater: {isMounted: ƒ, enqueueSetState: ƒ, enqueueReplaceState: ƒ, enqueueForceUpdate: ƒ}
__isMounted: false
__reactInternalMemoizedMaskedChildContext: {isInAParentText: false, onFocusRequested: undefined, focusEmitter: undefined}
__reactInternalMemoizedMergedChildContext: {rootTag: 31, isInAParentText: true, store: {…}, storeSubscription: null, navigation: {…}}
__reactInternalMemoizedUnmaskedChildContext: {rootTag: 31, isInAParentText: false, store: {…}, storeSubscription: null, navigation: {…}}
_getText: ƒ ()
_inputRef: null
_lastNativeText: ""
_onBlur: ƒ ()
_onChange: ƒ ()
_onFocus: ƒ ()
_onPress: ƒ ()
_onScroll: ƒ ()
_onSelectionChange: ƒ ()
_onTextInput: ƒ ()
_reactInternalFiber: FiberNode {tag: 2, key: null, type: ƒ, stateNode: {…}, return: FiberNode, …}
_reactInternalInstance: {_processChildContext: ƒ}
_renderAndroid: ƒ ()
_renderIOS: ƒ ()
_renderIOSLegacy: ƒ ()
_setNativeRef: ƒ ()
__proto__: ReactClassComponent

I'm using:
"react-native": "^0.54.0",
"react-native-masked-text": "^1.9.1",

Android Studio

Can someone please help point me to what is possibly going wrong? 

Brad 
bsselfridge@gmail.com

**Comment by josesuero** [comment]
You have to use ref instead of refInput

**Comment by benhurott** [comment]
Closing because @josesuero answered =).

**Comment by guisehn** [comment]
@benhurott README.md uses `refInput` + `getRawValue` on the example
