### ISSUE TITLE
this is possible make a mask with this format?

### ISSUE THREAD

**Issue by henriqueweiand** [benhurott/react-native-masked-text#109]
this is possible make a mask with this format? 

![kapture 2018-11-08 at 10 17 40](https://user-images.githubusercontent.com/6539492/48198304-8cd4c800-e33f-11e8-9e7f-7d41c29ef23b.gif)

i can`t define delimiter with false? right?

**Comment by benhurott** [comment]
Hi!

The better solution for what you want is to use a default textinput, convert the value into Number and apply decimal places.

You can see more info about decimal places in this link: https://www.w3schools.com/jsref/jsref_tofixed.asp
