### ISSUE TITLE
Custom Masked Input

### ISSUE THREAD

**Issue by tapdancemobile** [benhurott/react-native-masked-text#11]
Hey! Wondering if you had an example of how one would use your library to do a mask for a SSN. like take 111-11-1111 and mask it as XXX-XX-1111 while retaining the underlying value of 111-11-1111? Is this possible with the library?

**Comment by benhurott** [comment]
Hi,

I will improve the lib to let you change default mask characters.
Thanks for report =)

**Comment by benhurott** [comment]
Hi!

Sorry, i was on other galaxy.

Fixed in 1.5.0
