### ISSUE TITLE
Incorrect example on README.md

### ISSUE THREAD

**Issue by guisehn** [benhurott/react-native-masked-text#112]
The Usage section on the README file uses `refInput={(ref) => this.myDateText = ref}` to set the reference and then shows how to get the value by using `this.myDateText.getRawValue()`.

I kept getting the `getRawValue is not a function` error today when trying to do that and found this issue where someone said `ref` should be used instead of `refInput`:

https://github.com/benhurott/react-native-masked-text/issues/105

With that, it looks like the example on README.md is incorrect.

**Comment by guisehn** [comment]
I've created a pull request to address this issue:

https://github.com/benhurott/react-native-masked-text/pull/113

**Comment by benhurott** [comment]
Thanks brow o/
