### ISSUE TITLE
Como desenvolver uma validação de CPF

### ISSUE THREAD

**Issue by Uphero** [benhurott/react-native-masked-text#114]
Agora que consigo fazer uma mascara para o CPF com o método de  benhurott/react-native-masked-text
 encontrei outro problema: Como  definir uma função de validação para o CPF digitado.
Até agora só encontrei funções voltadas para JS e não tão dedicadas a RN, gostaria de saber por onde posso começar...

PS: estou desenvolvendo o código pelo expo snack.

Segue o código:
  
import * as React from 'react';
import {
  Text,
  View,
  StyleSheet,
  Button,
  TextInput,
  Alert,
} from 'react-native';
import { Constants } from 'expo';
import { TextInputMask } from 'react-native-masked-text';

export default class App extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      cpf: null,
      cpfmask: null,
    };
  }

  onPress(cpf) {
    let newtext: '';
    if (this.state.cpf.length < 11) {
      Alert.alert('Muito curto');
      this.setState({ cpf: newtext });
    }

    if (this.state.cpf.length == 11) {
      Alert.alert('Verificando...');
    }
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.paragraph}>Digite seu cpf</Text>
        <Text style={styles.paragraph}>{this.state.cpf}</Text>

        <TextInput
          style={{ height: 40, borderColor: 'gray', borderWidth: 1 }}
          onChangeText={cpf => this.setState({ cpf })}
          value={this.state.cpf}
          maxLength={11}
          keyBoardType={'numeric'}
        />
        <TextInputMask
          style={styles.paragraph}
          refInput={ref => (this.cpf = ref)}
          customTextInputProps={{
            style: { width: '80%' },
            label: 'CPF',
          }}
          maxLength={14}
          keyBoardType={'numeric'}
          type={'datetime'}
          options={{
            format: '999.999.999-99',
          }}
          onChangeText={cpf => this.setState({ cpf })}
          value={this.state.cpf}
        />

        <Button title=" a button" 
                     onPress={cpf => this.onPress(cpf)} 
          />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
  paragraph: {
    backgroundColor: 'lightgray',
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});

**Comment by benhurott** [comment]
Use this: https://github.com/benhurott/react-native-masked-text#methods

**Comment by Uphero** [comment]
Poderia dar alguma dica de como aplicar o

let valid = this.myDateText.isValid();

Sempre que tento não reconhece  ths.myDateText.isValid()


Em seg, 10 de dez de 2018 às 16:11, Ben-hur Santos Ott <
notifications@github.com> escreveu:

**Comment by benhurott** [comment]
Search for `call react component methods`.
This is a basic knowledge of react. Will be easy to find =).

**Comment by deyvisonborges** [comment]
const formatarSaidaCPF = () => {
        const value = String(dadosCPF);
        return value
            .replace(/\D/g, '')
            .replace(/(\d{3})(\d)/, '$1 $2')
            .replace(/(\d{3})(\d)/, '$1 $2')
            .replace(/(\d{3})(\d{1,2})/, '$1 $2')
            .replace(/(-\d{1})\d+?$/, '$1 ')
    };
