### ISSUE TITLE
Display the separator before the month for a datetime type

### ISSUE THREAD

**Issue by dngconsulting** [benhurott/react-native-masked-text#121]
Hello, 

Is it possible to display the first separator as soon as the user has typed the 2 chars day for a field configured as 'datetime' type with option => DD/MM/YYYY. The current behavior display the separator (slash) only when the user begin to type the first char of the month which is somewhat disturbing.

Thanks 

Sami

**Comment by benhurott** [comment]
Hi, no, it's not available.
This UI behaviour is something really personal, some guys don't like your behaviour, some guys like it.
Never ending story =P
