### ISSUE TITLE
Obfuscated credit card mask

### ISSUE THREAD

**Issue by donatoaz** [benhurott/react-native-masked-text#122]
Hi Guys!

I am using v1.10.1 with react-native 0.57.1.

I've been trying to understand how to use the obfuscated feature of credit cards when using a `TextInputMask` component.

When I pass the `{obfuscated: true}` options object to the component, this is what happens:

![react-native-masked-text](https://user-images.githubusercontent.com/127527/51406041-1aeadd00-1b3f-11e9-97da-c1b25f0b2c4b.gif)

And the thing is it works when not using obfuscation.

```javascript
import { TextInputMask } from 'react-native-masked-text'

const CustomTextInput = ({name, value, type, refInput, options}) => {
  const handleChangeText = (text) => {
    let inputValue = text
    onChangeText(name, inputValue)
  }

  const inputProps = {
    onChangeText: handleChangeText,
    value: value,
  }

  return (
          <TextInputMask
            {...inputProps}
            type={type}
            options={options}
            ref={refInput}
          />
  )
}
```

And where I use it (on a Formik form)

```javascript
        <CustomTextInput
          name={`${keyName}.CC`}
          type="credit-card"
          options={{ obfuscated: true }}
          value={CC}
          onChangeText={setFieldValue}
          refInput={this.refInput[6]}
        />
```

Any hints on how to fix this?

**Comment by benhurott** [comment]
Sorry man, I didn't understood the problem.
The obfuscated param just allow the user to put the first 4 and the last 4 digits of the credit card.

Can you give me the `what is happening` and `what should happen`?

**Comment by donatoaz** [comment]
Hi @benhurott obrigado pela resposta!

So, my apologies, I thought it was like a partial `secureTextEntry` in which only parts of the input are obfuscated.

I have this use case in which I need a `secureTextEntry` but with a social security mask, so the input should take numbers and show as `***-**-9999` with only the last four numbers showing up in the end. Do you see anyway of accomplishing that with a `type='custom'` `TextInputMask`?

Abraço e sempre bom ver uma lib legal mantida por brasileiro!!

**Comment by benhurott** [comment]
Hi @donatoaz !
Yes, if you want to use some custom, please, use the [type=custom](https://github.com/benhurott/react-native-masked-text#options). You can set the translator to ignore the `*` mask pattern.
Ask me if you need some help with this.

Abraço, tamo junto =)

**Comment by sun20173600** [comment]
I need mask of credit card type. I want to make a mask like this 4444 **** **** **** 5555 but it allows me to input only first 4 digits and last 4 digits.
@benhurott , you mentioned you could use type=custom. It would be great if you can give sample.
Regards
