### ISSUE TITLE
Use custom mask with type: cel-phone

### ISSUE THREAD

**Issue by RajanJS** [benhurott/react-native-masked-text#124]
I want to do something like this:

```
<TextInputMask
            type={'cel-phone'}
            style={styles.numberInput}
            options={{
              dddMask: '(99) 9999 - 9999'
            }}
/>

```
But while getting MaskService.getMask()

I'm getting extra mask characters;
(99) 9999 - 99999999-9999

Did I used it wrong or there's issue with the cel-phone type?

**Comment by benhurott** [comment]
Yes, you are using a complete mask inside the dddMask.
You don't need to use it because the default is `(99) `.
Just remove the options and it will work fine.

**Comment by RajanJS** [comment]
@benhurott Thanks for your quick response.

What if I want to use different mask other than (99) 9999-9999 or (99) 99999-9999
Ex: 99 - 99-999999

Can't we replace the default mask with our own mask completely?

**Comment by benhurott** [comment]
Yes, but you should use the `custom-mask`.

**Comment by RajanJS** [comment]
@benhurott ok thanks but would be a good feature to have replaced the default mask for cel-phone type too. As for using MaskService, we have to write own validators right?
