### ISSUE TITLE
It's possible to change color and fontSize of the placeholder?

### ISSUE THREAD

**Issue by unidospelosoftware** [benhurott/react-native-masked-text#133]
Hello! 

I'm trying to change the default color of the placeholder to another color, but I don't have found on the options something explains how I can do that. 😢

**Comment by benhurott** [comment]
Hi,

Could you check if you can change the color and fontSize of a normal `TextInput`?
Please, provide a code working with normal react-native text input and not working with masked text input, ok?

o/

**Comment by unidospelosoftware** [comment]
I was able to resolve the problem with normal react-native properties! 😆 

Thanks o/
