### ISSUE TITLE
Need HELP with mask

### ISSUE THREAD

**Issue by Mactub07** [benhurott/react-native-masked-text#135]
I have a mask for credit card  
options={{ mask: '{{9999}} {{9999}} {{9999}} {{9999}} {{999}}', obfuscated: false }}

I see in input http://prntscr.com/n4kc3f, I'm not sure is "{{" and "}}" should be visible?

code:

          <TextInputMask
            type={'custom'}
            options={{ mask: '{{9999}} {{9999}} {{9999}} {{9999}} {{999}}', obfuscated: false, }}
            value={this.state.text}
            onChangeText={text => {
              this.setState({
                text: text
              })
            }}
          />

**Comment by benhurott** [comment]
Hi, here is the docs: https://github.com/benhurott/react-native-masked-text#custom

you don't need to use the `{{` or `}}` just `9999 9999 9999 9999 999`
