### ISSUE TITLE
Git repo checked in?

### ISSUE THREAD

**Issue by jcroft** [benhurott/react-native-masked-text#140]
The most recent changes from a few hours ago result in this on successive npm installs:

npm ERR! path /Users/jcroft/Dropbox/GitHub/thebloxoffice-native/node_modules/react-native-masked-text
npm ERR! code EISGIT
npm ERR! git /Users/jcroft/Dropbox/GitHub/thebloxoffice-native/node_modules/react-native-masked-text: Appears to be a git repo or submodule.
npm ERR! git     /Users/jcroft/Dropbox/GitHub/thebloxoffice-native/node_modules/react-native-masked-text
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jcroft/.npm/_logs/2019-04-08T01_54_41_908Z-debug.log

Thanks for a great package!

**Comment by cihanbas** [comment]
I have same issue

**Comment by benhurott** [comment]
Hey @jcroft could you provide more info how to reproduce this issue?

What I did:

* I created a new expo project
* I installed the dependency
* I tested with a CPF mask

It worked properly.

**Comment by jcroft** [comment]
Will have more time to give you exact steps later, but what I was noticing was that it only happened on *repeat* installations of a project's deps. So, when I created a new project and installed react-native-masked-text, saving it to my package.json, there was no problem. But the next time I needed to npm install, I would get this error. I could uninstall the package, and again it would work on the first install but not on successive ones. Hope this helps for now. I downgraded to 1.11.1 and have no problems with it. :)

**Comment by ahce** [comment]
I have the same problem, only works in the first install. 

Environment
- Windows 10 1809
- node 10.15.3
- npm 6.9.0

**Comment by benhurott** [comment]
Ok guys what I did:

I added the `.git` folder to the `.npmignore`.
I tried to install and reinstall and it worked properly but probably you need to remove the `react-native-masked-text` folder from the `node_modules` and install it again.

Sorry for the inconvenience =/
