### ISSUE TITLE
Issue on type={'money'}

### ISSUE THREAD

**Issue by marmagzzz** [benhurott/react-native-masked-text#148]
I have the same error. I'm using iOS Simulator. I am using Expo SDK 30.
Saw the same issue with this https://github.com/benhurott/react-native-masked-text/issues/95
but the difference is the type of mask is money. Though, I already tried the _only-numbers_ and it works but this type of masking does not allow any precision/delimiters/etc.

![image](https://user-images.githubusercontent.com/44355605/56629284-73ba9c00-667f-11e9-93c2-539b63186c7c.png)

![image](https://user-images.githubusercontent.com/44355605/56629330-96e54b80-667f-11e9-9751-203a3a928706.png)

**Comment by marmagzzz** [comment]
Btw, I am using this on android and it works fine.

**Comment by marmagzzz** [comment]
I tried to downgrade the version for my iOS to 1.10.1, no luck, same error.

**Comment by benhurott** [comment]
Hi @marmagzzz 
You are setting the raw value to the state value.
In this case, try make this change:

```js
<TextInputMask
  // ...
  
  onChangeText={text => {
    this.setState(state => (
      {
        ...state,
        inputs: {
          ...state.inputs,
          probability: this.componentId['probablility'].getRawValue(),
          probabilityMasked: text
        }
      }
    ))
  }}
  value={this.state.inputs.probabilityMasked}
/>
```

**Comment by marmagzzz** [comment]
Hello, thanks for the respond @benhurott .
I will try on that. Thank you!

**Comment by marmagzzz** [comment]
![image](https://user-images.githubusercontent.com/44355605/56700608-c5216480-672d-11e9-894b-180e3b9b42f9.png)

It's working now. Thanks!
