### ISSUE TITLE
Use of regex

### ISSUE THREAD

**Issue by stvmachine** [benhurott/react-native-masked-text#150]
I'm trying to add a regular expression. For example, I'm trying to do something that recognizes: `22-222-21`, `22233-1-2`. That means the regex has to be something like:

```
([A-Z0-9])*-([A-Z0-9])*-([A-Z0-9])*
```

So, I'm not sure how many characters are going to be included, but I know the pattern. This is not possible?

**Comment by benhurott** [comment]
Hi @stvmachine 
The masks of this library are used for fixed value structure.
What you can do is create 2 `custom` masks, one for the `22-222-21` and another for `22233-1-2` and, depends on the value, change components dynamically.
For the samples you provide, is practically impossible to handle as a mask, once they have the same char length and same value structure (numbers and dashes).
The question is: if the user type `22` then type `3`. What should be the behavior? `223` or `22-3`?
For this reason, is currently not supported.
