### ISSUE TITLE
The props testID and accessibilityLabel are not passed to RN TextInput

### ISSUE THREAD

**Issue by cassioseffrin** [benhurott/react-native-masked-text#156]
I am trying extract the props testID and accessibilityLabel with Appium for automated tests, but those props aren't passed out to the low level component TextInput that appears on the screen.

May those important props could be passed through the TextInputMask to the RN TextInput, so we will be able to get it in Selenium.

**Comment by benhurott** [comment]
Hi @cassioseffrin !
We passed all the props to the text input.
Could you provide a code sample of the component to let me analyze if something is missing?

**Comment by benhurott** [comment]
Closing due inactivity

**Comment by vinscloudthing** [comment]
Hi, would like to have testId prop for testing, please take a look at the screen shot.


![Screenshot 2021-06-21 at 7 38 24 PM](https://user-images.githubusercontent.com/73094837/122776225-89ac6180-d2c8-11eb-8927-7cb69a5c5dba.png)

**Comment by timotgl** [comment]
@vinscloudthing `testID` is spelled with an uppercase `D` (at least in RN 0.71).
