### ISSUE TITLE
allowFontScaling Not Working

### ISSUE THREAD

**Issue by TheJackTenor** [benhurott/react-native-masked-text#158]
Hello. I found that when passing `allowFontScaling` and set it to `false`, there will be a glitch. When `allowFontScaling` prop is passed, the fontsize should be like the top form

![Mask Bug](https://user-images.githubusercontent.com/32075564/57566770-dd4ce100-73c7-11e9-9ac9-adeec52bb395.gif)

**Comment by benhurott** [comment]
Hey man, could you provide a code sample?

**Comment by benhurott** [comment]
Closing due inactivity
