### ISSUE TITLE
Remove moment.js dependency

### ISSUE THREAD

**Issue by pcooney10** [benhurott/react-native-masked-text#160]
Hey @benhurott, awesome library !

Would you be open to removing the `type={'datetime'}` functionality, so we can remove the `moment.js` dependency? As you mentioned in #61, we can already implement custom masks in user land!

Removing this dependency would decrease the bundle size substantially, as moment currently accounts for 85% ([source](https://bundlephobia.com/result?p=react-native-masked-text@1.12.2)):

![image](https://user-images.githubusercontent.com/11021913/57657383-34f67280-75a9-11e9-89b6-892e24723073.png)

If you want to keep things the way they are, I totally understand. Just wanted to float the idea !

**Comment by benhurott** [comment]
Hi, @pcooney10 !
Yes, I can remove, but I need to keep the same functionality.
It can cause breaking changes, so, it should be removed carefully.

**Comment by Johny1010** [comment]
You can always use for example date-fns, which is 10 times lighter
I can prepare pull request

**Comment by marcinkrysiak1979** [comment]
dayjs is 2kb bundle size, immutable and the API is compatible with moment.js

**Comment by marcinkrysiak1979** [comment]
PR here: #186

**Comment by benhurott** [comment]
done o/

**Comment by pcooney10** [comment]
Nice @marcinkrysiak1979 !!

![image](https://user-images.githubusercontent.com/11021913/63553520-a4fd8880-c508-11e9-8205-e436b9cbcac6.png)

**Comment by marcinkrysiak1979** [comment]
My pleasure :)
