### ISSUE TITLE
getRawValue returns the incomplete value

### ISSUE THREAD

**Issue by alessandrosales** [benhurott/react-native-masked-text#161]
![image](https://user-images.githubusercontent.com/8078636/57870738-175e1e80-77de-11e9-83c9-3567d5c3671a.png)

When I type the value (85) 99999-8877 the value returned by getRawValue removes the last character: 8599999887

Other example:
![image](https://user-images.githubusercontent.com/8078636/57871295-622c6600-77df-11e9-9cdb-d01483c96724.png)

Nativebase: ^2.12.1
react-native-masked-text: ^1.9.2 (already tested with the latest version, the same problem occurs)

This problem was not happening, it happened after I updated the version of nativebase. This happened to occur with all the masks. 

Has anyone ever had this problem?

**Comment by benhurott** [comment]
Hey man, the problem is because you are getting the raw value `before` setting the state.
To avoid this behavior, use this helper:
https://github.com/benhurott/react-native-masked-text#including-the-rawtext-in-onchangetext-1120

If you still have a problem, feel free to reopen the issue, ok?

**Comment by alessandrosales** [comment]
This suggestion solved my problem. Thank you

**Comment by JereLima** [comment]
Component
```
<TextInputMask
        includeRawValueInChangeText={true}
        type={type}
        value={value}
        options={options}
        onEndEditing={onEndEditing}
        onChangeText={onChangeText}
        style={{fontSize: 20, paddingLeft: 10, width: '100%'}}
        placeholder={placeholder}
        onChange={onChange}
        ref={ref}
      />
```


Screen


```
<InputMask
        value={price}
        onChangeText={(masked, unmasked) => setPrice(unmasked)}
        placeholder="Valor total"
        type="money"
      />
```
