### ISSUE TITLE
Default values do not initialize with masks

### ISSUE THREAD

**Issue by alessandrosales** [benhurott/react-native-masked-text#162]
![image](https://user-images.githubusercontent.com/8078636/57901933-72732e00-783d-11e9-960e-bda111f5d5e3.png)

After typing the mask is applied, however, the value initially loaded through the state does not have the mask applied.

This problem did not occur before.

**Comment by benhurott** [comment]
Hi @alessandrosales could you provide a `code sample`?

**Comment by alessandrosales** [comment]
![image](https://user-images.githubusercontent.com/8078636/57930332-09ff6d80-788c-11e9-8c4e-c661fb0900ce.png)

![image](https://user-images.githubusercontent.com/8078636/57930343-15529900-788c-11e9-9688-b81ac3fc3a79.png)

![image](https://user-images.githubusercontent.com/8078636/57930354-1edc0100-788c-11e9-85bb-f4a3490b1656.png)

![image](https://user-images.githubusercontent.com/8078636/57930372-27ccd280-788c-11e9-83f4-457d2f673235.png)

**Comment by benhurott** [comment]
Fixed in `1.12.3`.
Thanks for reporting bro o/

**Comment by alessandrosales** [comment]
Thanks
