### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by horacioh** [benhurott/react-native-masked-text#168]
how hard it would be to enable web support on this module? I would love to contribute on it!

**Comment by benhurott** [comment]
Hi @horacioh thanks for your request.
Currently I have no idea of how hard it can be, sorry =P.

For web, I think we have other great libraries available.

**Comment by horacioh** [comment]
ok no problem!
did you close it because there's no interest on adding support?
I asked because I'm now working on a project where we are using React Native Web and would be nice to use the same library to all platforms.

anyway, I understand if its not a priority! :)

thanks again!
