### ISSUE TITLE
No inputText

### ISSUE THREAD

**Issue by humbertocruz** [benhurott/react-native-masked-text#18]
Hello, I am very new on React Native. I put this component on my "login" component but the input do not shows up. I'm using native-base and follow the exact example but just the "Label" show on the form. Even the space where the input should be is not showing.

thanks

**Comment by benhurott** [comment]
Hi,

Please, paste the code here to let me analyse it =).

**Comment by benhurott** [comment]
Hi,

I'm closing this issue because no information was provided.
If you want, reopen with sample of code to let me analyse =).
