### ISSUE TITLE
CPF, CNPJ, and Zip-Code mask don't work

### ISSUE THREAD

**Issue by akinncar** [benhurott/react-native-masked-text#180]
When I try to use cpf and cnpj mask on react-native 0.60, my screen don't render without errors.
In the same input, if I try to use cel-phone or only-numbers mask, it works.
Somebody have idea to solve or maybe has been through it???

I'm using react-native-masked-text: 1.12.4

**Comment by benhurott** [comment]
Hi, please provide a code sample.

**Comment by akinncar** [comment]
I was copying my code to provide and I found my error, the default state of value provide in Input was false, but the correct is "", look:

<h3>Simplify Code</h3>

 Wrong:
```  javascript
import { InputMask } from "react-native-masked-text";


const [registerNumber, setRegisterNumber] = useState(false);  // error here

<InputMask
      mask="cpf"
      keyboardType="numeric"
      placeholder={`Digite seu CPF`}
      value={registerNumber}
      onChangeText={setRegisterNumber}
/>
```

 Correct:
```  javascript
import { InputMask } from "react-native-masked-text";


const [registerNumber, setRegisterNumber] = useState("");  // solve here

<InputMask
      mask="cpf"
      keyboardType="numeric"
      placeholder={`Digite seu CPF`}
      value={registerNumber}
      onChangeText={setRegisterNumber}
/>
```
