### ISSUE TITLE
TextInputMask doesnt render mask correctly when type change

### ISSUE THREAD

**Issue by RodrigoAWeber** [benhurott/react-native-masked-text#184]
I have a situation where i need to change the mask of TextInputMask as the state change, but it doesnt change.

project template: **react-native init test**

`
import React from "react";
import { DropDown } from "secullum-react-native-ui";
import { TextInputMask } from "react-native-masked-text";

class App extends React.Component {
  state = {
    tipoDocumento: "cnpj",
    documento: ""
  }

  render () {
    const documentos = [
      { label: "CNPJ", value: "cnpj" },
      { label: "CPF", value: "cpf" },
      { label: "Outro Documento", value: "only-numbers" }
    ];

    return (
      <>
        <DropDown
          label={"Tipo de documento"}
          items={documentos}
          value={this.state.tipoDocumento}
          onChange={value => this.setState({ tipoDocumento: value })}
        />
        <TextInputMask
          type={this.state.tipoDocumento}
          value={this.state.documento}
          keyboardType="numeric"
          onChangeText={value => this.setState({ documento: value })}
        />
      </>
    );
  }
};

export default App;
`

**workaround**

`
import React from "react";
import { DropDown } from "secullum-react-native-ui";
import { TextInputMask } from "react-native-masked-text";

class App extends React.Component {
  state = {
    mask: "99.999.999/9999-99",
    documento: ""
  }

  render () {
    const documentos = [
      { label: "CNPJ", value: "99.999.999/9999-99" },
      { label: "CPF", value: '999.999.999-99" },
      { label: "Outro Documento", value: "99999999999" }
    ];

    return (
      <>
        <DropDown
          label={'Tipo de documento'}
          items={documentos}
          value={this.state.mask}
          onChange={value => this.setState({ mask: value })}
        />
        <TextInputMask
          type={'custom'}
          options={{
            mask: this.state.mask
          }}
          value={this.state.documento}
          keyboardType="numeric"
          onChangeText={value => this.setState({ documento: value })}
        />
      </>
    );
  }
};

export default App;
`

  "dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-masked-text": "^1.12.5",
    "secullum-react-native-ui": "^1.2.6"
  }

**Comment by RodrigoAWeber** [comment]
this commit causes the issue https://github.com/benhurott/react-native-masked-text/commit/0eff65324c6dfc53e45a57829270a2aedf600e70

Its comparing the same this.props.type

**Comment by benhurott** [comment]
done o/
