### ISSUE TITLE
Error: Passing props inside type="" doesn't work

### ISSUE THREAD

**Issue by lancaluis** [benhurott/react-native-masked-text#188]
I'm creating a generic TextInput using 'react-native-masked-text', but I cannot pass props inside type="", how is it works?

`<TextInputMask
          {...props}
          type={this.props.type} // HERE
          ...
  />`

**Comment by benhurott** [comment]
`{...props}` -> `{...this.props}`?

**Comment by lancaluis** [comment]
I don't understand your question, but my code is here: 

**GenericTextInput**
`<TextInputMask
          {...this.props}
          type={this.props.type}
          style={styles.input}
          autoCapitalize="none"
          autoCompleteType="off"
          autoCorrect={false}
        />`

**When I use GenericTextInput**
`<Input
                  type={'cel-phone'}
                  options={{
                    maskType: 'BRL',
                    withDDD: true,
                    dddMask: '(99) '
                  }}
                  value={values.mobilePhone}
                  onChangeText={handleChange('mobilePhone')}
                  blur={() => setFieldTouched('mobilePhone')}
                  label="Celular"
                />`

but doesn't works :/. Could you help me?

**Comment by benhurott** [comment]
You are using in the first part:
```
{...props}
```
And in the second part
```
{...this.props}
```

Probably one of them is wrong. Did you debugged this part to check what have inside the `...props` and what have inside the `this.props`?

I think you should add `this.` to `...props` (`...this.props`) or remove the `this` in `this.props.type`.

**Comment by lancaluis** [comment]
> You are using in the first part:
> 
> ```
> {...props}
> ```
> 
> And in the second part
> 
> ```
> {...this.props}
> ```
> 
> Probably one of them is wrong. Did you debugged this part to check what have inside the `...props` and what have inside the `this.props`?
> 
> I think you should add `this.` to `...props` (`...this.props`) or remove the `this` in `this.props.type`.

I solved it, but when I have input without mask, doesn't works because type="" is required. How can I change type="" as optional props?

**Comment by benhurott** [comment]
Just render a normal text input instead the masked text input.
For now this how the community is handling this behaviour.

**Comment by lancaluis** [comment]
> Just render a normal text input instead the masked text input.
> For now this how the community is handling this behaviour.

Thanks man! It works :)
