### ISSUE TITLE
TextInputMask size on Android

### ISSUE THREAD

**Issue by Miiiiii7** [benhurott/react-native-masked-text#190]
I was using the textInputMask and noticed that the size on Android is larger.
How can I customize the size for Android? When I set a specific height, it cuts the data.
Bellow is the screenshot of both platforms.

![TextInputMask_IOS](https://user-images.githubusercontent.com/52251891/63601506-f014ab80-c59b-11e9-977e-296564a2cb5a.png)
![TextInputMask_Android](https://user-images.githubusercontent.com/52251891/63601507-f0ad4200-c59b-11e9-9f16-6d1a772de733.png)

Here is a sample code used.

```
import React, { Component } from 'react';
import { View, Text } from 'react-native';
import { TextInputMask } from 'react-native-masked-text';

export default class UselessTextInputMultiline extends Component {
  render() {
    return (
      <View style={{margin:30}}>
        <View style={{ flexDirection: 'row', justifyContent: 'space-between',alignItems: 'center' }}
        >
          <Text>
            Quantity
          </Text>
          <TextInputMask
            type="only-numbers"
            value={1}
            editable={false}
          />
      </View>
        <View style={{ flexDirection: 'row', justifyContent: 'space-between',alignItems: 'center' }}
        >
          <Text>
            Price
          </Text>
          <TextInputMask
            type="money"
            value={99.9}
            options={{
              precision: 2,
              separator: ',',
              delimiter: '.',
              unit: '$ ',
              suffixUnit: '',
            }}
            editable={false}
          />
      </View>
     </View>
    );
  }
}
```

**Comment by benhurott** [comment]
Hi, the `TextInputMask` uses the default TextInput.
Could you try the normal text input and check if the same error occurs?

**Comment by Miiiiii7** [comment]
I found out what was happening.
It occurs on TextInput either.

Android adds some default padding on top and bottom, so you have to reset them by adding padding: 0 to your element' style.

Thanks
