### ISSUE TITLE
fromMask to Value

### ISSUE THREAD

**Issue by sibelius** [benhurott/react-native-masked-text#2]
is it possible to go from the masked value to the value without mask?

for instance:

`R$ 10,20` to `10.20`

**Comment by benhurott** [comment]
Hi!

It's in my TODO list =). For now, is not possible =/.

**Comment by sibelius** [comment]
maybe u could store both value (masked and raw), and let the user access both 

I'm not sure what is the best way to add this to the API

by the way I did a template to use this package with tcomb-form-native: https://gist.github.com/sibelius/c564ded5bfd39534cf035e0460f2ee9a

**Comment by benhurott** [comment]
Hi @sibelius 

I'm closing this issue because i release the version 1.2.0 with the `getRawValue` method.

Thanks =).

**Comment by sibelius** [comment]
Tks
