### ISSUE TITLE
I need to add something like placeholder

### ISSUE THREAD

**Issue by cuonghv91** [benhurott/react-native-masked-text#20]
Im trying to set up a placeholder for my TextInputMask, but how ?

**Comment by cuonghv91** [comment]
Oh my bad !!

Its very easy, You just set the initial value on constructor then it will be the placeholder :), something like this : 

constructor(props){
   super(props);
   this.state = {
      initialValue: 'My Placeholder'
   }
}

And then in the  TextInputMask, use the attribute : 

value={this.state.textInput2}

**Comment by cuonghv91** [comment]
Oh No !!

What if I set up type={'money'}, but I want to make my placeholder as string like "I want this to be placeholder" ??

**Comment by benhurott** [comment]
Hi =),

Fixed at [1.3.4](https://github.com/benhurott/react-native-masked-text/releases/tag/1.3.4)

Thanks for reporting =)
