### ISSUE TITLE
getRawValue missing data

### ISSUE THREAD

**Issue by Skynear2** [benhurott/react-native-masked-text#200]
Good morning, I'm new to react native but I came across an error. Using the getValueRaw function to return the actual value of the input, I noticed that a number is always missing, for example:
Input:      |                   Return:
R$00,05 |                    NaN
R$0,50    |                    0.05
R$05,00  |                    0.50

Code: 

```
<TextInputMask
              type={'money'}
              options={{
                precision: 2,
                separator: ',',
                delimiter: '.',
                unit: 'R$',
                suffixUnit: ''
              }}
              ref={(ref) => this.rawValue = ref}
              value={this.state.valueCurrency
              style={styles.inputMoney}
              onChangeText={valueCurrency => {
                this.setState({ valueCurrency })
                console.log(this.rawValue.getRawValue())
            }}/>

**Comment by Skynear2** [comment]
I noticed that the problem of missing a number is in the react native text input along with saving straight into the component state.
Since the problem is not with `react-native-masked-text` I'll be closing the issue.

**Comment by lucasvieceli** [comment]
como você resolveu ?
