### ISSUE TITLE
Ability to set custom ref for textinput in order to use with module such as "react-native-keyboard-aware-scrollview"

### ISSUE THREAD

**Issue by parijatsahai** [benhurott/react-native-masked-text#21]
Nice component! Could you please enhance it to allow custom REF to be passed as a prop so that it can be used with a module such as "react-native-keyboard-aware-scrollview"? 

The main issue I'm facing with this component is that the text input hides behind the keyboard when it gains focus, and I need an ability to move the text input above the keyboard.

Thanks.

**Comment by benhurott** [comment]
Hi =)

Is not component's responsability to move screen to avoid keyboard behavior.
You can use the [KeyboardAvoidingView](https://facebook.github.io/react-native/docs/keyboardavoidingview.html) to handle this problem.
It solve some most issues about keyboard and padding screen.
