### ISSUE TITLE
Money mask doesn't allow input greater than 999.99

### ISSUE THREAD

**Issue by waterydan** [benhurott/react-native-masked-text#226]
Hi, how do I allow money input greater than 999.99? Somehow it resets to 0 if I try to enter '1999.99'? 

Here's my code:

<TextInputMask
    type="money"
    options={{ precision: 2, separator: ".", delimiter: ",", unit: "$" }}
    value={formikProps.values.amountReceived.toString()}
    onChangeText={text => formikProps.setFieldValue("amountReceived", Number(text.replace("$", "")))}
    style={{ fontSize: 16 }}
/>

**Comment by cinder92** [comment]
@waterydan did you find a solution for this? im having same issue

**Comment by Vasault** [comment]
having the same issue
