### ISSUE TITLE
TextInputMask + Unform + Yup

### ISSUE THREAD

**Issue by JulianoBazzi** [benhurott/react-native-masked-text#227]
Good night.
Is it possible to use TextInputMask with Unform and Yup?

**Comment by alikrodrigues** [comment]
I need use with unform too,  I can't get the element value for my registerField.. it's just when use the TextInputMask

**Comment by RodriguesCosta** [comment]
hi, the @Rocketseat team updated the docs to include instructions for this implementation, view this link for instructions https://unform.dev/examples/react-native-input-mask

**Comment by JulianoBazzi** [comment]
Thank you.
