### ISSUE TITLE
Reference error

### ISSUE THREAD

**Issue by silasrm** [benhurott/react-native-masked-text#27]
Hi,

I'm trying to use ref props but when I'm using `this.refs['field']` this error occurs:
![screenshot_1497479579](https://user-images.githubusercontent.com/197187/27157597-c28c46de-5138-11e7-8c33-2c8086d24f0b.png)

My code:

```
<TextInputMask
  style={styles.input}
  keyboardType="numeric"
  ref={'cpf'}
  type={'cpf'}
  customTextInput={Input}
  value={this.props.profileEdit.cpf}
  onChangeText={value => this.props.changeProfileEditCpf(value)}
/>
```

My line error: `console.log('CPF ', this.refs['cpf']);`

ESLINT says use `this.refs` is deprecated.

RN version is 0.42.3

Any suggestion?

**Comment by benhurott** [comment]
Hi!

Can you paste entire js file code here?

**Comment by silasrm** [comment]
@benhurott,

I chose not to use this to get the value without the mask. But the code is this. 
The console log is inside a form button onPress function.

**Comment by benhurott** [comment]
I test this:

![image](https://user-images.githubusercontent.com/3187772/27248894-730438fc-52e0-11e7-9c34-c4550d1e87ed.png)

And works as expected.

Can you send me how you set the button function?

**Comment by benhurott** [comment]
Hi, i'm closing this issue. If the error persist, please, send-me the code and open another issue. Thanks =).
