### ISSUE TITLE
Value resets when parent's state changes

### ISSUE THREAD

**Issue by JulioC** [benhurott/react-native-masked-text#30]
If you have a the a TextInputMask inside a component and this component re-renders due to a state change, the TextInputMask resets its value.

The same doesn't happen with TextInput.

**Comment by benhurott** [comment]
Hi, can you paste here a sample of code?

**Comment by JulioC** [comment]
This should be enough to reproduce it

```js
import React from 'react';
import { TextInput, View } from 'react-native';
import { TextInputMask } from 'react-native-masked-text';

class Form extends React.Component {
  state = {
    simple: '',
    masked: '',
  }

  render() {
    const { price } = this.state;
    return (
      <View>
        <TextInput
          onChangeText={(simple) => this.setState({ simple })}
        />
        <TextInputMask
          getRawValue={(text) => Number(text.replace(/[^0-9\.]+/g, ""))}
          onChangeText={(masked) => this.setState({ masked })}
          type="money"
        />
      </View>
    );
  }
}

export default Form;
```

My package versions are:

```
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-masked-text": "^1.5.3",
```

**Comment by benhurott** [comment]
Sorry, this is my mistake to not put this sample on docs.
Just set `value={this.state.masked}` to your component.

```jsx
<TextInputMask
          getRawValue={(text) => Number(text.replace(/[^0-9\.]+/g, ""))}
          onChangeText={(masked) => this.setState({ masked })}
          type="money"
          value={this.state.masked}
        />
```

Tell me if it works, ok?

**Comment by JulioC** [comment]
Yeah, that is the workaround I was using.

Wouldn't it be better to emulate the same behavior from TextInput?

**Comment by benhurott** [comment]
I will change some things to keep the same behavior.

Thanks for reporting =).

**Comment by ronilitman** [comment]
@benhurott Any update on this?

**Comment by rejjer** [comment]
@ronilitman I fixed this by updating the key prop of the parent component.
This causes the component to be remounted, but if at that time input has a focus - it needs to be manually installed again.
