### ISSUE TITLE
`datetime` mask allows invalid data

### ISSUE THREAD

**Issue by pukhalski** [benhurott/react-native-masked-text#33]
Having `type="datetime"` and `format` as `"MM/YY"` allows to enter any numeric characters, e.g `99/00` or `13/22` which are not valid month numbers I assume.

**Comment by pukhalski** [comment]
Also, `format` could be even `"XX / XX"` — it doesn't matter what alphabetic chars to use.

**Comment by benhurott** [comment]
Hi, 
The component only mask values.
For validation, use the method [isValid](https://github.com/benhurott/react-native-masked-text#methods)

**Comment by pukhalski** [comment]
Thanks,
but it would be nice not to allow users to enter invalid values. I know that it is a bit compex but still feasible tbh

**Comment by wincod75** [comment]
Any update on this?

**Comment by benhurott** [comment]
A million years later:

You can check if the date is valid calling the `isValid` method:
[datetime.isValid](https://github.com/benhurott/react-native-masked-text#methods-4)

I can't find any way to block the user without compromise the experience.
I'm closing this issue, for now, I will reopen in feature if I found some solution.
