### ISSUE TITLE
Problem with removing characters in the middle of the mask

### ISSUE THREAD

**Issue by Oxyaction** [benhurott/react-native-masked-text#35]
**v1.6.1**
Having the following input
```
<TextInputMask
  type="custom"
  options={{ mask: '999 (99) 999 99 99' }}
/>
```
If I'll type **380934295576** the mask will display correct value like **380 (93) 429 55 76**
But if I remove the **2** from the middle of the mask it will display **380 (93) 49**,
instead of **380 (93) 495 57 6**.

I've made some research and figured that problem is in passing value to tinymask that is already masked. in this particular case the value **380 (93) 49 55 76** is passed to the `mask` method and since space after **9** char doesn't match to numeric wildcard all the following chars are getting trimmed.

Suggest passing normalized value to `mask`

**Comment by benhurott** [comment]
Hi!

Thanks for reporting =).
I fix it at `1.6.2`, but a little know issue still remain for white spaces (not affect your scenario).

**Comment by valeryq** [comment]
@benhurott Hi, it should be reopened. That's because not all cases were covered.
Same example as @Oxyaction, but if I'll type 38093429557 (without last digit) the mask will display correct value **380 (93) 429 55 7** and if I remove the **2** from the middle of the mask it will display **380 (93) 495 57** (it's correct), but cursor jumping before **4** that's because last white space also deleting from the masked value.

Any idea to fix this?

**Comment by benhurott** [comment]
Hi,

Can you tell me the following informations?

* React-Native version
* SO (Android or iOS) and version
* Version of react-native-masked-text

**Comment by valeryq** [comment]
@benhurott
**React Native**: 0.47.1
**OS**: iOS and Android
**react-native-masked-text**: 1.6.2

**Comment by benhurott** [comment]
Nice, 

I will reopen the issue.

**Comment by IgorSorokopud** [comment]
Hi,
in v1.6.2 issue with the next scenario is reproduced:

fill in field "Phone number" +123 (45) 678 90.
Move the cursor to number "5", and click delete button - cursor is jump to number "2", and deleted all numbers after "4"

**Comment by megabayt** [comment]
+1 waiting for fix

**Comment by AndrewTotsky** [comment]
+1 waiting for fix

**Comment by IgorSorokopud** [comment]
It helped me:

<TextInputMask
  type="cel-phone"
  options={{ dddMask: '+999 (99) 999 99 99' }}
/>

**Comment by AndrewTotsky** [comment]
me need mask +7 999 999-99-99

**Comment by benhurott** [comment]
Guys, I fix some issues about these scenarios in `1.9.0`.

I'm still facing a little issue with cursor but for now, some of them are fixed.

**Comment by StanislavVoronov** [comment]
In my case type "credit-card" and mask "9999 9999 9999 9999". I'm starting to remove characters in the middle of each four block and something strange is happening, but making some changes, at least, it has right order.

**Comment by Boolkast** [comment]
Can u make phone mask?
+7 999 999 9999 for example?

**Comment by benhurott** [comment]
Fixed at 1.11.1 after a thousand years.

**Comment by Singh-Aish** [comment]
can we remove a substring based on the pattern? having a hard time!!
my scenario:
Input string: hi {5be80e1a35126b6523601e09 | Aishwarya} was here!!
Expected Output: hi Aishwarya was here!!

basically, i want to remove the id embedded in the string

**Comment by Miilla** [comment]
Hello,
i have this problem on iOS only - cant remove separtor if cursor is not on the end of string.
![aa](https://user-images.githubusercontent.com/28782088/60979108-6fbf2180-a332-11e9-8895-920b27d2f5ab.gif)

**React Native:** 0.58.3
**OS:** iOS (12.1)
**react-native-masked-text:** 1.12.3

TextInputMask values:
```
type={'custom'}
options={{
   mask: '999 999 999 999'
}}
```
@benhurott can you help me? :)

**Comment by AlexanderKaplunsky** [comment]
> Hello,
> i have this problem on iOS only - cant remove separtor if cursor is not on the end of string.
> ![aa](https://user-images.githubusercontent.com/28782088/60979108-6fbf2180-a332-11e9-8895-920b27d2f5ab.gif)
> 
> **React Native:** 0.58.3
> **OS:** iOS (12.1)
> **react-native-masked-text:** 1.12.3
> 
> TextInputMask values:
> 
> ```
> type={'custom'}
> options={{
>    mask: '999 999 999 999'
> }}
> ```
> 
> @benhurott can you help me? :)

Any workaround for this issue..?

**Comment by Findiglay** [comment]
The issue seems to only apply to custom masks

**Comment by coolirisroto** [comment]
:( any updateS?
