### ISSUE TITLE
defaultValue prop not supported?

### ISSUE THREAD

**Issue by Maj0rPaine** [benhurott/react-native-masked-text#43]
Does v1.6.2 not support defaultValue prop for TextInput component? If not, what's the best approach to setting a persisted value without having to keep the state in sync? 
Looks like this was removed in v1.3.4 in favor of a placeholder prop.

**Comment by daviscabral** [comment]
I believe it is forwarded to the component automatically.

**Comment by silasmatheus** [comment]
+1

**Comment by andrewfluck** [comment]
@Maj0rPaine use `value`, that sets the default value as far as I'm aware

**Comment by Maj0rPaine** [comment]
@andrewfluck you can use the value prop to set an initial value but then it's up to you to keep the controlled state in sync. Using the [defaultValue ](https://facebook.github.io/react-native/docs/textinput.html)prop of the underlying TextInput component sets the initial value which is what I was after. I ended up just exposing the MaskService to handle the masking instead of using the TextMask component.
