### ISSUE TITLE
Maximum amount of money?

### ISSUE THREAD

**Issue by andrewfluck** [benhurott/react-native-masked-text#48]
Can you add an option that limits the amount of money you can input? I desperately need this feature.

**Comment by benhurott** [comment]
Hi!

You can use [checkText](https://github.com/benhurott/react-native-masked-text#checktext) and [getRawValue](https://github.com/benhurott/react-native-masked-text#methods) combined =)

**Comment by ManigandanRaamanathan** [comment]
@benhurott can you provide example for limiting maximum x amount?
