### ISSUE TITLE
Space between unit and amount

### ISSUE THREAD

**Issue by slawder** [benhurott/react-native-masked-text#5]
I'm using the money mask on text input and notice there's an extra space between my "$" and amount. For example : "$ 8.25" instead of "$8.25". 

Is this space intentional and or any way to remove it?

**Comment by benhurott** [comment]
Hi!

This is a limitation of the `vanilla-masker` dependency:
![image](https://cloud.githubusercontent.com/assets/3187772/21011368/0526e99e-bd38-11e6-9bc0-bdf902739fa4.png)

I will change this to accept space or remove them and use exactly what you pass in the `unit` parameter.

If you pass `unit: '$ '` it will have a blank space. If you pass `unit: '$'` you will have no blank space.

Thanks for comment =).

**Comment by slawder** [comment]
Ah that makes sense. I was looking through the source code for your extension and was confused why I couldn't find it anywhere. Thanks!

**Comment by benhurott** [comment]
Hi, fixed in `1.2.1` =)
