### ISSUE TITLE
[Question]  input text for hashtags 

### ISSUE THREAD

**Issue by sandropoluan** [benhurott/react-native-masked-text#53]
I need an input text that only for hashtags value (unlimited hashtags ).
For example
#computer #game #sport #cpu 

What i need.
1. Only support alphanumeric and underscore .
2.  Unlimited hastags

How can I achieve it?
Thank you

**Comment by benhurott** [comment]
Hi,

This component is for masked values, not for tags or hashtags.
Please, take a look in this lib: [react-native-tag-input](jwohlfert23/react-native-tag-input)

See you later =)
