### ISSUE TITLE
Add raw value to onTextChange

### ISSUE THREAD

**Issue by malashkevich** [benhurott/react-native-masked-text#55]
Hello!
Masking usually used for UX. For data flows inside the app better raw input. It would be cool if masked text input pass in onTextChange two values: masked and raw.

**Comment by LuisRizo** [comment]
That is a good recommendation, I was attempting to get the raw input on the onChangeText function but had to use this as a workaround.
```
<TextInputMask
ref={ref => this.amountRef = ref}
type="money"
value={this.state.amount}
onChangeText={amount => this.setState({amount: this.amountRef.getRawValue()})}
/>
```

**Comment by dfsilva** [comment]
+1

**Comment by questionablequestion** [comment]
#138
