### ISSUE TITLE
maxLenght set with the mask

### ISSUE THREAD

**Issue by Mate38** [benhurott/react-native-masked-text#58]
At maxLenght you have to count the spaces and symbols of the mask together, it would be interesting that when putting the mask of, for example CPF, this already limited to 14 characters.

This avoids the effect of writing and erasing when you pass the mask border

**Comment by benhurott** [comment]
Hi,

Closing it by duplicating of [issue 56](https://github.com/benhurott/react-native-masked-text/issues/56)
