### ISSUE TITLE
Use validation without mask

### ISSUE THREAD

**Issue by Mate38** [benhurott/react-native-masked-text#59]
It would be interesting to add the library the possibility of not applying mask but use the validation, for example for emails

**Comment by benhurott** [comment]
Hi,

It's possible (and already in the docs).

Take a look at the [DOCUMENTATION](https://github.com/benhurott/react-native-masked-text#extra-maskservice)

**Comment by Mate38** [comment]
I had already seen but from what I understood there would compare if the string would be compatible with the mask, however I do not see how to validate an email through a mask since the size can be variable

**Comment by benhurott** [comment]
The lib is used for masked values.
E-mail is not a masked value, you can use a regex with normal textinput component.
