### ISSUE TITLE
Optional characters in mask

### ISSUE THREAD

**Issue by chapati23** [benhurott/react-native-masked-text#6]
hey,
first of all thanks for writing this, already saved me a lot of time :)

my question:
i need a mask that has a range of characters (vs a fixed amount).

_______________ / ______
^ 2-10 chars.....  ^ 2-6 chars

is this possible with the current implementation?

i saw that for the `cel-phone` mask you have optional length (8 or 9 digits) but this functionality doesn't seem to be exposed to the `custom`-mask, or am I overlooking something here?

**Comment by benhurott** [comment]
Hi! in next weekend i will test and answer this =).

**Comment by benhurott** [comment]
Hi, it's not possible because the code doesn't know where the 3th charactere will be inputed.
In the case: 
* when i insert `2`, the mask will be `2______________ / ______`.
* when i insert `8`, the mask will be `28_____________ / ______`.
* when i insert 4... mind blow. Correct is `284_____________ / ______` or `28_____________ / 4_____`?

For that reason is not possible.

Sorry =/

**Comment by chapati23** [comment]
you're right, didn't think this through logically…

but what about if it was only 1 field:

____________
^ 6-9 chars

and i want a space after every 3rd character. that'd be no logical issue. but you'd need to be able to specify a range somehow (similar to the 8- or 9-digit cell-phone validation)

**Comment by benhurott** [comment]
Hi!

Sorry, i was killing zombies for a long time.

Fix in 1.5.0.

You now can use this:

```jsx
<TextInputMask
    style={styles.input}
    type={'custom'}
    options={{
        mask: '*** *** ***'
     }} />
```

**Comment by nagapriyanka93** [comment]
@chapati23  did u get the solution?

**Comment by ThomasStubbe** [comment]
I have the same request. I would like to use this library for IP-Addresses 999.999.999.999 where 99.99.99.99 and 9.9.9.9 should also be possible... Something like this: 9{1,3}.9{1,3}.9{1,3}.9{1,3}
