### ISSUE TITLE
Using native TextInput onSubmitEditing() to focus on TextInputMask

### ISSUE THREAD

**Issue by gabriellim** [benhurott/react-native-masked-text#60]
```
<TextInput
  ref='input1'
  onSubmitEditing={ () => this.refs.input2.focus() } />

<TextInputMask
  ref='input2' />
```
After typing some text into input1 and pressing the submit button I get an error _this2.refs.input2.focus is not a function, it is undefined. 

Is it possible to focus from TextInput to TexInputMask?

**Comment by shadowbrush** [comment]
@gabriellim: you want to use `getElement`: `this.refs.input2.getElement().focus()`

**Comment by gabriellim** [comment]
@shadowbrush is getElement only required for this component? I didn't have to use it for multiple native TextInputs

```
<TextInput
  ref='input1'
  onSubmitEditing={ () => this.refs.input2.focus() } />

<TextInput
  ref='input2'
  onSubmitEditing={ () => this.refs.input3.focus() } />

<TextInput
  ref='input3'
  onSubmitEditing={ () => this.refs.input4.focus() } />
...
````

**Comment by benhurott** [comment]
Hi,

This behavior is described [HERE](https://github.com/benhurott/react-native-masked-text#textinput-methods).

**Comment by acomito** [comment]
@gabriellim did you solve this? I'm having the same problem. Had it working with native text input.

**Comment by TatianaOnishi** [comment]
@gabriellim @acomito do you guys have found a solution? I'm having the same problem. 
I tried to follow the [example](https://github.com/benhurott/react-native-masked-text-samples/blob/master/ReactNativeMaskedTextSamples/Samples/FocusingNextInput.js) and that [way](https://github.com/benhurott/react-native-masked-text/issues/13) but none worked :(
