### ISSUE TITLE
Date fns instead of moment js

### ISSUE THREAD

**Issue by ODelibalta** [benhurott/react-native-masked-text#61]
I installed this lib in an instant because it is something I need but I really do not like moment js. I believe date fns is a much lighter faster lib. I am looking at other libs now that this is using momentjs.

**Comment by benhurott** [comment]
Hi,

You can create a custom masked text using `type={'custom'}`, creating validation methods and bla bla bla.

[HERE](https://github.com/benhurott/react-native-masked-text#type) is the initial docs for it.

See you later =)
