### ISSUE TITLE
How can i mask a decimal value?

### ISSUE THREAD

**Issue by cbfranca** [benhurott/react-native-masked-text#64]
I'm trying to mask a decimal value, but i can't did this.

Something like a repetition pattern would work too.

ex: [0-9]-[0-9]*

Any idea?

Tks

**Comment by p-ugulino** [comment]
I usually do something like: "999-999"

**Comment by benhurott** [comment]
Sorry for the time, I was lost in another galaxy.

I don't understand the problem, can you tell me more details?

You want your value shows as `9-9`?

**Comment by benhurott** [comment]
Hi, did you look at [money mask](https://github.com/benhurott/react-native-masked-text#options)?

**Comment by cbfranca** [comment]
Maybe I can use money mask setting unit to blank...

**Comment by benhurott** [comment]
Yep,

For now, I will close this issue. Feel free to reopen if needed =).

**Comment by cbfranca** [comment]
@benhurott , how can i add more than two decimal cases to money type?
