### ISSUE TITLE
Can't create custom translator that allows a space

### ISSUE THREAD

**Issue by ryanhomer** [benhurott/react-native-masked-text#65]
Great component! I have a custom mask and it's almost complete in its functionality but I'm having trouble creating a custom translator.

I want to allow a mask character, say '#', to allow alphanumeric or a space. However, the translator function never receives the space. That is, when a space is inputted, the translator function doesn't get called. Instead, the space is removed somewhere else so I never get a chance to intercept it.

Is there a way to allow a space in the mask without an actual space in the mask string? If not, can you point me to where in the code the space is being removed?

**Comment by ryanhomer** [comment]
I found it. It's `removeWhileSpaces` in `custom.mask.js`:

	getValue(value, settings) {
		if (value === '') {
			return value;
		}
		let { mask } = settings;
		let translation = this.mergeSettings(DEFAULT_TRANSLATION, settings.translation);

		var masked = new TinyMask(mask, { translation }).mask(this.removeWhiteSpaces(value));
		return masked;
	}

Any suggestions on how to work around this are welcome.

**Comment by benhurott** [comment]
Hi, i'm little busy at now.
I will see this soon as possible.

Thanks for reporting.
