### ISSUE TITLE
date masking is allowing user to enter alphabets

### ISSUE THREAD

**Issue by anveshreddy87** [benhurott/react-native-masked-text#69]
Hi,
Date masking is allowing user to enter alphabets and moreover it is accepting too many characters.
Please help me how can i restrict not to accept alphabets when user enters (developing app for iPads)....Thanks

below is Code and package json details:

Package Json: 

"react": "16.3.1",
    "react-native": "0.55.2",
    "react-native-masked-text": "^1.6.5",
    "react-native-material-kit": "^0.5.1",

export default class App extends Component<Props> {
render() {
    return (
      <View style={styles.container}>
       
        <View style={{flex:1}}>
        <TextInputMask
				ref={'myDateText'}
        type={'datetime'}
        customTextInput={TextfieldWithFloatingLabel}
				options={{
					format: 'DD-MM-YYYY'
				}}
			/>
        </View>
        <View style={{flex:1,backgroundColor:'green'}}>
        <Text>hi</Text>
        </View>
        
      </View>
)
}
}

<img width="389" alt="screen shot 2018-04-18 at 8 34 44 pm" src="https://user-images.githubusercontent.com/22500378/38965012-2cc969d0-4348-11e8-934f-563a70e5b860.png">
<img width="373" alt="screen shot 2018-04-18 at 8 35 43 pm" src="https://user-images.githubusercontent.com/22500378/38965013-2cde92a6-4348-11e8-9807-6151ce8615fb.png">

**Comment by benhurott** [comment]
Hi, this can be because this [ISSUE](https://github.com/benhurott/react-native-masked-text/issues/68).

I will close it and after I resolve that issue it occurs again, I will reopen.

Thanks for reporting
