### ISSUE TITLE
undefined is not a function (evaluating 'babelHelpers.typeof(exports)')

### ISSUE THREAD

**Issue by barakcoh** [benhurott/react-native-masked-text#7]
Hi

I'm getting this error after installing `react-native-masked-text`. Seems to be originating from the included `.babelrc`. If I remove the `es2015` preset, it works. 

Running on React Native 0.39.2.

This is my `.babelrc`

```
{
  "passPerPreset": true,
  "sourceMaps": "inline",
  "presets": [
    "react-native"
  ],
  "plugins": [
    "./plugins/babelRelayPlugin",
    "transform-flow-strip-types",
    "transform-class-properties"
  ]
}
```

Would it be possible to either remove th `es2015` preset or distribute a transpiled version to npm?

![image](https://cloud.githubusercontent.com/assets/566186/22208130/6d443484-e18a-11e6-9806-1bf9573c221a.png)

**Comment by benhurott** [comment]
Hi,

Fixed at https://github.com/benhurott/react-native-masked-text/commit/25176a1d339aa117eafbfc656cffb914733f225d
