### ISSUE TITLE
Flickering effect when input

### ISSUE THREAD

**Issue by anniewey** [benhurott/react-native-masked-text#71]
Especially when press 'Delete' button. Any workaround for this to make it looks smoother?

**Demo video:**
[https://drive.google.com/open?id=1c_8O9RCqXhTW2xeCqTQ5O6aWrwMNfeo1](url)

**Comment by benhurott** [comment]
Hi, 

Are you run your app in debug or release mode?

Because it's appear to be related to [Issue #12](https://github.com/benhurott/react-native-masked-text/issues/12).

**Comment by anniewey** [comment]
Hi, the effect is seen in both debug and release mode. Is there any workaround than using the solution suggested in #12?

**Comment by benhurott** [comment]
Hi, for now, use that tricks =).

**Comment by pavlokitdev** [comment]
@anniewey
Hi! Did you have luck in using solution suggested in #12 ? It don't work for me :(
I'm using TextInputMask with type={'money'} and I have exactly same ugly effect as you show in video.

Thanks

**Comment by Benzer1406** [comment]
I have the same issue, I tried the work around proposed from #12 , but didn't work because the this.props.type was always undefined.

**Comment by dhonaldJC** [comment]
> @pavlokitdev Hi, I wasn't able to get it work back then and didn't use this component anymore

what component do you use for this one my friend??

**Comment by cenaHara** [comment]
same issue hi @dhonaldJC , @all any solution
