### ISSUE TITLE
Custom input

### ISSUE THREAD

**Issue by conradoramalho** [benhurott/react-native-masked-text#75]
Is it possible to use a custom input component?

**Comment by benhurott** [comment]
Hi,

Reading the docs: yes.
[DOCS](https://github.com/benhurott/react-native-masked-text#customtextinput)

**Comment by johhansantana** [comment]
this doesn't work if the custom component is a functional component. Gives me ```Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?```

**Comment by ctodarealpro** [comment]
> this doesn't work if the custom component is a functional component. Gives me `Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

Hi, its happening with me to, did you discover how to fix it?

**Comment by Coystark** [comment]
> > this doesn't work if the custom component is a functional component. Gives me `Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`
> 
> Hi, its happening with me to, did you discover how to fix it?

Same here, anyone knows how to fix it?

**Comment by johhansantana** [comment]
I don’t quite remember but probably using a regular class component or forking this and refactor code to support hooks and what not.

**Comment by PauloMarceloNogueira** [comment]
Same here, anyone knows how to fix it?

**Comment by nikola166** [comment]
Just use class Component for you custom Input
