### ISSUE TITLE
Need to partially mask a text field

### ISSUE THREAD

**Issue by NativeMan99** [benhurott/react-native-masked-text#76]
I have a username that i need to partially mask it for security reasons. For example, if the user name is "username99", it has to display "use*******".

How would we write a custom mask for this 

Please let me know

**Comment by benhurott** [comment]
Hi,

If you want to display text instead have text-input, you can use the [MaskedText](https://github.com/benhurott/react-native-masked-text#usage-textmask) with [Custom Translation](https://github.com/benhurott/react-native-masked-text#options).

Just override the `*` symbol.
