### ISSUE TITLE
Change text with masked input using virtual keyboard

### ISSUE THREAD

**Issue by vinipachecov** [benhurott/react-native-masked-text#77]
Hi there, I'm using virtual keyboard for a specific screen and would like to know if it's possible to use money mask withouth a textinput but using a Text component.
Something that could work like this: 
https://www.jqueryscript.net/demo/jQuery-Currency-Input-Filed-Mask-Plugin-maskmoney/

**Comment by benhurott** [comment]
Hi,

Yes, just use it: [textmask](https://github.com/benhurott/react-native-masked-text#usage-textmask)

**Comment by vinipachecov** [comment]
Thanks! I have misunderstood the usage of this component :)
