### ISSUE TITLE
getElement() return undefined

### ISSUE THREAD

**Issue by herlan-evocorp** [benhurott/react-native-masked-text#79]
I need to navigate between TextInput and TextInputMask using focus (), but the call to the getElement () method returns undefined.

My Method:

`
focusNextField(id) {
if (this.refs[id].getElement) {
this.refs[id].getElement().focus();
} else {
this.refs[id].focus();
}
};
`

My Component:

`<TextInputMask
onChangeText={documento => this.setState({documento})}
value={documento}
autoCapitalize={'none'}
autoCorrect={false}
keyboardType={'numeric'}
type={'cpf'}
underlineColorAndroid='transparent'
ref={'cpf'}
onSubmitEditing={() => this.focusNextField('telefone')}
returnKeyType={'next'}
blurOnSubmit={false}
/>`

**Comment by benhurott** [comment]
Hi, thanks for reporting.

I found the bug and I will be fixed in the next version.

**Comment by benhurott** [comment]
Hi!

Fixed at 1.7.2!
