### ISSUE TITLE
es2015 preset on .babelrc

### ISSUE THREAD

**Issue by vagnercsouza** [benhurott/react-native-masked-text#8]
Hi,

I recently installed this package on an app that I'm developing and was working fine, but today, when I did a npm update, the following error started showing: 

`Couldn't find preset "es2015" relative to directory`

After research, i figured out that the problem is the "es2015" preset on .babelrc file. After I removed it, the app worked fine. I tested the TextInputMask and it worked fine without the "es2015" preset.

So, I think that it can be removed from the repo.

**Comment by vagnercsouza** [comment]
#9

**Comment by benhurott** [comment]
Thanks for the PR =)

**Comment by basequatro** [comment]
Shouldn't also be removed from dev dependencies?
"babel-preset-es2015": "^6.22.0",
