### ISSUE TITLE
onTextChange stop mask working

### ISSUE THREAD

**Issue by Igorpollo** [benhurott/react-native-masked-text#81]
Hi.

When I use

```
          <TextInputMask
                style={styles.input}
                refInput={(ref) => this.myDateText = ref}
                placeholder="Telefone"
                onChangeText={(telefone) => {console.log(telefone)}}
                type={'cel-phone'}
              />
```

the input mask works but if I change OnChangeText to this:

`onChangeText={(telefone) => {this.setState(telefone)}}
`

Can help pls?

**Comment by benhurott** [comment]
Hi!

Did you mean `onChangeText={(telefone) => {this.setState({ telefone })}}` ?
Obs: we change the `(telefone)` to `({ telefone })`
