### ISSUE TITLE
Using onlyNumber and CreditCard together

### ISSUE THREAD

**Issue by nimamyscreen** [benhurott/react-native-masked-text#82]
I'm implementing an App only for iPad and in iPad keyboardType="numeric" is not supported.So I need to use onlyNumber and Credit-card types together .

**Comment by benhurott** [comment]
Hi, 
Sorry, but I do not understand the problem.
You can pass your own keyboard type to the component.

[Take a look at the documentation](https://github.com/benhurott/react-native-masked-text#textinput-props):

> if you pass keyboardType, it will override the keyboardType of masked component.

This resolves your issue?

**Comment by benhurott** [comment]
After some investigation, I discover it's caused by a RN Bug.
Take a look at https://github.com/benhurott/react-native-masked-text/issues/68.

This is an issue that occurs only in iOS.

**Comment by nimamyscreen** [comment]
@benhurott , yes I confirm that RN 0.55.0 has this bug , I downgraded to 0.53.0 and It's working well.
