### ISSUE TITLE
custom type for all characters 

### ISSUE THREAD

**Issue by nimamyscreen** [benhurott/react-native-masked-text#85]
I have a list of inputs and some of these inputs need to work as normal input and accept all kind of characters and some of them don't. So I need something like this : 

` <TextInputMask
            type="custom"
           options ={mask:'all character'}
          />`

**Comment by benhurott** [comment]
Hi,

Please, read the documentation [HERE](https://github.com/benhurott/react-native-masked-text#options).

You can pass custom translator to custom mask.

**Comment by Marcuspo** [comment]
How i can write mask with text lenght with 255 characters?
