### ISSUE TITLE
How to setup a guide for custom masks

### ISSUE THREAD

**Issue by die20** [benhurott/react-native-masked-text#86]
Hey! 

I'm looking to find a way to setup a guided mask for custom settings. 

For example, 

If the custom mask is `*** ****`, 
when a user types in `th` I'd like the input field to look like `th_ ____`

Any ideas?

Thanks in advance for the help!

**Comment by benhurott** [comment]
Hi

If you want to keep the `_`, I think it's better you use a fixed text and use the [Mask Service](https://github.com/benhurott/react-native-masked-text#extra-maskservice) when the user changes the text.

**Comment by vseverestek** [comment]
> Hey!
> 
> I'm looking to find a way to setup a guided mask for custom settings.
> 
> For example,
> 
> If the custom mask is `*** ****`, when a user types in `th` I'd like the input field to look like `th_ ____`
> 
> Any ideas?
> 
> Thanks in advance for the help!

Were You able to do it?
can you share an example?
