### ISSUE TITLE
credit-card: Only input 10 digits

### ISSUE THREAD

**Issue by shamanking** [benhurott/react-native-masked-text#87]
With document:
credit-card: use the mask 9999 9999 9999 9999

But I only input 10 digits (ext: 4222 4222 42)

 "react-native-masked-text": "^1.7.2",
"react": "16.3.1",
"react-native": "~0.55.4",

**Comment by benhurott** [comment]
Hi

Can you send a sample of the code you're using?

**Comment by shamanking** [comment]
@benhurott : I'm so sorry, I use props maxLength and I forget to remove it
