### ISSUE TITLE
Unable to resolve module ./masks in v1.9.0

### ISSUE THREAD

**Issue by ahce** [benhurott/react-native-masked-text#92]
I upgrade 1.7.2 to 1.9.0 and gets this error:
bundling failed: Error: Unable to resolve module ./masks

React-native v0.55.4

**Comment by benhurott** [comment]
Fixed at [1.9.1](https://github.com/benhurott/react-native-masked-text/releases/tag/1.9.1).
Sorry for this nooooob mistake hahahaha.
