### ISSUE TITLE
Usage with no mask

### ISSUE THREAD

**Issue by donatoaz** [benhurott/react-native-masked-text#94]
I would like to be able to use this component without a mask, or a mask that allows any value. How can that be accomplished?

I tried setting the mask to a simple `'*'`, but evidently that did not work.

**Comment by benhurott** [comment]
Hi, this component is for masked values.
If you want to use this without a mask, just make a render condition and use the default text input:
```
if (this.state.useMask) {
  // return masked input
}
else {
  // return normal text input
}
```

This will result in a more performant component because the mask checks a lot of things when the user types the text.
